// electron-builder config — JS form so we can read env vars at config-load
// time. Previously this was electron-builder.yml, but `${env.VAR}` substitution
// in yml runs AFTER schema validation, so strict enum fields like
// publish.releaseType and publish.channel rejected the literal placeholders.
//
// All four VALOR_* env vars are set by scripts/build.mjs based on --channel.
// Sane defaults below let bare `npx electron-builder` runs (without going
// through build.mjs) still produce a stable build.
//
// Filename matters: electron-builder auto-detects `electron-builder.js` but
// NOT `.config.cjs`. Treated as CommonJS because package.json has no
// "type": "module".
//
// Note: register-scheme is stubbed out by scripts/build.mjs before this
// config is even loaded — that's why there's no native rebuild hook here.

const channel       = process.env.VALOR_UPDATER_CHANNEL  || 'latest'
const channelSuffix = process.env.VALOR_CHANNEL_SUFFIX   || ''
const releaseType   = process.env.VALOR_RELEASE_TYPE     || 'release'

/** @type {import('electron-builder').Configuration} */
module.exports = {
  appId: 'uk.co.dawn-star.valor-client',
  productName: 'VALOR',
  copyright: 'Copyright © 2025 VALOR',

  // ── Output ─────────────────────────────────────────────────────────────────
  directories: {
    buildResources: 'build',
    output: 'dist',
  },

  files: ['out/**/*'],

  // ── Extra resources (accessible at runtime via process.resourcesPath) ──────
  extraResources: [{ from: 'icon/logo.png', to: 'icon.png' }],

  // ── Auto-update publish target ─────────────────────────────────────────────
  // Publishes to GitHub Releases. Run `npm run release:win:<channel>` to build
  // + upload. Requires GH_TOKEN env variable (GitHub PAT with repo scope).
  //
  // All three channels publish to the same repo with different update feeds:
  //   stable → channel=latest  → latest.yml  → releaseType=release
  //   seth   → channel=seth    → seth.yml    → releaseType=prerelease
  //   brazen → channel=brazen  → brazen.yml  → releaseType=prerelease
  //
  // Stable releases are NOT marked prerelease so GitHub's /releases/latest
  // always points at the most recent stable build (which is where the
  // "Back to stable" button in non-stable banners sends users).
  publish: [
    {
      provider: 'github',
      owner: 'DevilGamin21',
      repo: 'VALOR-Client',
      channel,
      releaseType,
    },
  ],

  // ── Windows ────────────────────────────────────────────────────────────────
  win: {
    // mpv player — bundled from resources/mpv/ (shinchiro nightly builds).
    // Windows-only: Linux uses system-installed mpv from PATH.
    extraResources: [
      {
        from: 'resources/mpv',
        to: 'mpv',
        filter: ['**/*.exe', '**/*.dll'],
      },
    ],
    target: [{ target: 'nsis', arch: ['x64'] }],
    icon: 'icon/logo.png',

    // Channel-suffixed artifact name (suffix is empty for stable, "-seth" /
    // "-brazen" for non-stable). Stable installer stays as VALOR-Setup.exe so
    // the GitHub "latest" download URL is unchanged for existing users.
    artifactName: `VALOR-Setup${channelSuffix}.exe`,

    // No code-signing certificate — skip signing entirely so winCodeSign
    // (which contains macOS symlinks) is never downloaded on Windows.
    forceCodeSigning: false,
    sign: null,
    signingHashAlgorithms: null,

    // Explicit user-level manifest — never triggers UAC prompt
    requestedExecutionLevel: 'asInvoker',
  },

  // ── NSIS installer ─────────────────────────────────────────────────────────
  nsis: {
    // Full wizard mode — shows welcome, directory, install, finish pages
    oneClick: false,
    allowToChangeInstallationDirectory: false,
    allowElevation: false,
    perMachine: false,

    // Custom branding images (generated by scripts/generate-assets.mjs)
    installerSidebar: 'build/installerSidebar.bmp',  // 164×314 px — welcome/finish page left panel
    installerHeader: 'build/installerHeader.bmp',    // 150×57 px  — inner page header

    // Custom NSIS includes for welcome/finish page copy & colours
    include: 'build/installer.nsh',

    // Suppress the license agreement page (auto-detected from build/license.rtf otherwise)
    license: null,

    shortcutName: 'VALOR',
    createDesktopShortcut: true,
    createStartMenuShortcut: true,

    // Keep user data (electron-store JWT, etc.) on uninstall
    deleteAppDataOnUninstall: false,

    // Suppress non-fatal NSIS warnings from the include file
    warningsAsErrors: false,
  },

  // ── Linux ──────────────────────────────────────────────────────────────────
  linux: {
    target: [
      { target: 'AppImage', arch: ['x64'] },
      { target: 'deb',      arch: ['x64'] },
    ],
    icon: 'icon/logo.png',
    category: 'AudioVideo',
    maintainer: 'dawn-star.co.uk',
    // Channel-suffixed artifact name (suffix is empty for stable, "-seth" /
    // "-brazen" for non-stable). Stable artifacts keep their original names
    // for backwards compatibility with the GitHub "latest" download URL.
    artifactName: `VALOR-Setup${channelSuffix}.\${ext}`,
  },
}
